In [ ]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import tensorflow as tf
#from tensorflow import keras
import keras
from keras import layers, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
import os

In [ ]:
from keras.datasets import fashion_mnist

In [ ]:
(train_X,train_Y), (test_X,test_Y) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 1s 0us/step


In [ ]:
import numpy as np
from keras.utils import to_categorical
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
print('Training data shape : ', train_X.shape, train_Y.shape)

print('Testing data shape : ', test_X.shape, test_Y.shape)
class_name=['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle Boot']

Training data shape :  (60000, 28, 28) (60000,)
Testing data shape :  (10000, 28, 28) (10000,)


In [ ]:
train_Y[:10]

array([9, 0, 0, 3, 0, 2, 7, 2, 5, 5], dtype=uint8)

In [ ]:
test_Y[:10]

array([9, 2, 1, 1, 6, 1, 4, 6, 5, 7], dtype=uint8)

In [ ]:
train_X = train_X.reshape(-1, 28, 28, 1)

test_X = test_X.reshape(-1, 28, 28, 1)

train_X.shape, test_X.shape

((60000, 28, 28, 1), (10000, 28, 28, 1))

In [ ]:
train_X = train_X.astype('float32')
test_X = test_X.astype('float32')

In [ ]:
test_X[9000,27,15]

array([138.], dtype=float32)

In [ ]:
train_X = train_X / 255
test_X = test_X / 255

In [ ]:
test_X[9000,27,15]

array([0.5411765], dtype=float32)

In [ ]:
train_Y_one_hot = to_categorical(train_Y)
test_Y_one_hot = to_categorical(test_Y)
print('Original label:', train_Y[4738])
print('After conversion to one-hot:', train_Y_one_hot[4738])

Original label: 4
After conversion to one-hot: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
from sklearn.model_selection import train_test_split
train_X,valid_X,train_label,valid_label = train_test_split(train_X, train_Y_one_hot, test_size=0.2, random_state=13)

In [ ]:
batch_size = 64
epochs = 15
num_classes = 10

In [ ]:
!pip install tensorflow
import tensorflow as tf

In [ ]:
import keras
from keras.models import Sequential,Model
from tensorflow.keras.layers import Input
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
#from keras.layers.normalization import BatchNormalization
from tensorflow.keras.layers import BatchNormalization
#from keras.layers.advanced_activations import LeakyReLU
from tensorflow.keras.layers import LeakyReLU

# Load Fashion MNIST data
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

# Normalize the data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Reshape data
x_train = x_train.reshape((-1, 28, 28, 1))
x_test = x_test.reshape((-1, 28, 28, 1))

# Convert labels to one-hot encoding
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

fashion_model = Sequential()
fashion_model.add(Conv2D(32, kernel_size=(3, 3),activation='linear',input_shape=(28,28,1),padding='same'))
fashion_model.add(LeakyReLU(alpha=0.1))
fashion_model.add(MaxPooling2D((2, 2),padding='same'))
fashion_model.add(Conv2D(64, (3, 3), activation='linear',padding='same'))
fashion_model.add(LeakyReLU(alpha=0.1))
fashion_model.add(MaxPooling2D(pool_size=(2, 2),padding='same'))
fashion_model.add(Conv2D(128, (3, 3), activation='linear',padding='same'))
fashion_model.add(LeakyReLU(alpha=0.1))
fashion_model.add(MaxPooling2D(pool_size=(2, 2),padding='same'))
fashion_model.add(Flatten())
fashion_model.add(Dense(128, activation='linear'))
fashion_model.add(LeakyReLU(alpha=0.1))
fashion_model.add(Dense(num_classes, activation='softmax'))

# Compile the model
fashion_model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adam(),metrics=['accuracy'])
# Train the model
fashion_model.fit(x_train, y_train, batch_size=64, epochs=15, verbose=1, validation_data=(x_test, y_test))

# Mount Google Drive



Epoch 1/15
938/938 [==============================] - 7s 6ms/step - loss: 0.4423 - accuracy: 0.8386 - val_loss: 0.3328 - val_accuracy: 0.8784
Epoch 2/15
938/938 [==============================] - 5s 6ms/step - loss: 0.2758 - accuracy: 0.8991 - val_loss: 0.2648 - val_accuracy: 0.9043
Epoch 3/15
938/938 [==============================] - 5s 6ms/step - loss: 0.2276 - accuracy: 0.9167 - val_loss: 0.2429 - val_accuracy: 0.9141
Epoch 4/15
938/938 [==============================] - 5s 5ms/step - loss: 0.1986 - accuracy: 0.9263 - val_loss: 0.2570 - val_accuracy: 0.9102
Epoch 5/15
938/938 [==============================] - 6s 6ms/step - loss: 0.1730 - accuracy: 0.9364 - val_loss: 0.2326 - val_accuracy: 0.9178
Epoch 6/15
938/938 [==============================] - 5s 6ms/step - loss: 0.1532 - accuracy: 0.9428 - val_loss: 0.2278 - val_accuracy: 0.9189
Epoch 7/15
938/938 [==============================] - 6s 6ms/step - loss: 0.1323 - accuracy: 0.9505 - val_loss: 0.2551 - val_accuracy: 0.9115
Epoch 

In [ ]:
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/gdrive')

# Save the model to Google Drive
fashion_model.save('/content/gdrive/MyDrive/mnist/fashion222', save_format="h5")

Mounted at /content/gdrive


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
fashion_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 28, 28, 32)        320       
                                                                 
 leaky_re_lu_8 (LeakyReLU)   (None, 28, 28, 32)        0         
                                                                 
 max_pooling2d_6 (MaxPoolin  (None, 14, 14, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_7 (Conv2D)           (None, 14, 14, 64)        18496     
                                                                 
 leaky_re_lu_9 (LeakyReLU)   (None, 14, 14, 64)        0         
                                                                 
 max_pooling2d_7 (MaxPoolin  (None, 7, 7, 64)          0         
 g2D)                                                 

In [ ]:
from google.colab import drive
import os
from PIL import Image
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model


# Path to your saved model
model_path = '/content/gdrive/MyDrive/mnist/fashion222'

# Load your trained model
fashion_model = load_model(model_path)

# Define class labels for Fashion MNIST
class_labels = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
                "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

# Path to your image in Google Drive
image_path = '/content/gdrive/MyDrive/mnist/mnist paint/canta.png'
# Function to preprocess the image
def preprocess_image(image_path):
    # Load the image
    img = Image.open(image_path)
    # Resize the image to match the input shape of the model
    img = img.resize((28, 28))
    # Convert image to grayscale
    img = img.convert('L')
    # Convert image to numpy array
    img_array = np.array(img)
    # Reshape array to match the input shape of the model
    img_array = img_array.reshape((1, 28, 28, 1))
    # Normalize the image
    img_array = img_array / 255.0
    return img_array


def run_example(image_path):
# Preprocess the image
    preprocessed_image = preprocess_image(image_path)

# Perform prediction
    predictions = fashion_model.predict(preprocessed_image)
    predicted_class = np.argmax(predictions)
    confidence = predictions[0][predicted_class]  # Probability of the predicted class

# Convert confidence to percentage
    confidence_percent = round(confidence * 100, 10)

# Print the predicted class
    print("Predicted class:", class_labels[predicted_class])
    print("Confidence:", confidence_percent, "%")
    print()

run_example(image_path)



1/1 [==============================] - 0s 75ms/step
Predicted class: Bag
Confidence: 100.0 %

